### PR TITLE
Convert Swagger spec to Markdown

### PR DESCRIPTION
**Pull request by sommestad**
Convert Swagger spec to Markdown

Basic conversion of a Swagger spec to markdown format.

### CODE REVIEW

**Comment by sommestad** [comment]
I don't know why Travis doesn't start building. :construction_worker:

**Comment by sommestad** [comment]
Looks like Travis are doing some network maintenance. Maybe it'll start shortly.

**Comment by dbrockman** [comment]
- [x] main in package points to index.js, should be a file in lib

**Comment by dbrockman** [comment]
- [x] remove version field from package file. It will be set be semrel

**Comment by dbrockman** [comment]
- [x] The travis file has two after_success fields. Not sure that will work. Combine them into one list

**Pull request merged**
